# Generated by Django 3.2.3 on 2021-05-30 02:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Comuna',
            fields=[
                ('idComuna', models.AutoField(primary_key=True, serialize=False, verbose_name='Id de la Comuna')),
                ('nombreComuna', models.CharField(max_length=30, verbose_name='Nombre de la Comuna')),
            ],
        ),
        migrations.CreateModel(
            name='Contactanos',
            fields=[
                ('idContac', models.AutoField(primary_key=True, serialize=False, verbose_name='Id del Contactanos')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre del Usuario')),
                ('correo', models.CharField(max_length=100, verbose_name='Correo del Usuario')),
                ('asunto', models.CharField(max_length=50, verbose_name='Asunto del Contactanos')),
                ('comentario', models.CharField(max_length=500, verbose_name='Comentario del Contactanos')),
            ],
        ),
        migrations.CreateModel(
            name='Direccion',
            fields=[
                ('idDireccion', models.AutoField(primary_key=True, serialize=False, verbose_name='Id de la Direccion')),
                ('descripcion', models.CharField(max_length=50, verbose_name='Direccion')),
                ('numDic', models.IntegerField(verbose_name='Número de la Dirección')),
                ('blockDpto', models.CharField(max_length=5, verbose_name='Bloque del Departamento')),
                ('numDpto', models.CharField(max_length=5, verbose_name='Número del Departamento')),
                ('direccionDespacho', models.IntegerField(verbose_name='Corresponde a Direccion de Desspacho')),
                ('comuna', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AmonStore.comuna')),
            ],
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('idRegion', models.AutoField(primary_key=True, serialize=False, verbose_name='Id de la Región')),
                ('nombreRegion', models.CharField(max_length=30, verbose_name='Nombre de la Región')),
            ],
        ),
        migrations.CreateModel(
            name='TipoProducto',
            fields=[
                ('idTipoProd', models.AutoField(primary_key=True, serialize=False, verbose_name='Id del Tipo de Producto')),
                ('descripcion', models.CharField(max_length=30, verbose_name='Tipo de Producto')),
            ],
        ),
        migrations.CreateModel(
            name='TipoUsuario',
            fields=[
                ('idTipoUsu', models.AutoField(primary_key=True, serialize=False, verbose_name='Id del Tipo de Usuario')),
                ('descripcion', models.CharField(max_length=15, verbose_name='Tipo de Usuario')),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('rutUsu', models.CharField(max_length=20, primary_key=True, serialize=False, verbose_name='Rut del Usuario')),
                ('nombreUsu', models.CharField(max_length=50, verbose_name='Nombre del Usuario')),
                ('apellidoUsu', models.CharField(max_length=50, verbose_name='Apellido del Usuario')),
                ('correoUsu', models.CharField(max_length=100, verbose_name='Correo del Usuario')),
                ('contrasenaUsu', models.CharField(max_length=50, verbose_name='Contraseña del Usuario')),
                ('telefonoUsu', models.IntegerField(verbose_name='Telefono del Usuario')),
                ('tipousuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AmonStore.tipousuario')),
            ],
        ),
        migrations.CreateModel(
            name='Venta',
            fields=[
                ('factura', models.AutoField(primary_key=True, serialize=False, verbose_name='Número de la Factura')),
                ('fechaVenta', models.DateField(verbose_name='Fecha de la Factura')),
                ('total', models.IntegerField(verbose_name='Total de la Factura')),
                ('estado', models.IntegerField(verbose_name='Estado de la Factura')),
                ('direccion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AmonStore.direccion')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AmonStore.usuario')),
            ],
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('idProducto', models.AutoField(primary_key=True, serialize=False, verbose_name='Id del Producto')),
                ('nombreProd', models.CharField(max_length=30, verbose_name='Nombre del Producto')),
                ('precioProd', models.IntegerField(verbose_name='Precio del Producto')),
                ('descripcionProd', models.CharField(max_length=200, verbose_name='Descripcion del Producto')),
                ('fotoProd', models.ImageField(upload_to='', verbose_name='Foto')),
                ('stockProd', models.IntegerField(verbose_name='Stock del Producto')),
                ('tallaProd', models.CharField(max_length=3, verbose_name='Talla del Producto')),
                ('colorProd', models.CharField(max_length=10, verbose_name='Talla del Producto')),
                ('tipoproducto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AmonStore.tipoproducto')),
            ],
        ),
        migrations.AddField(
            model_name='direccion',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AmonStore.usuario'),
        ),
        migrations.CreateModel(
            name='DetalleVenta',
            fields=[
                ('idDetalle', models.AutoField(primary_key=True, serialize=False, verbose_name='Id del Detalle de la Venta')),
                ('cantidadProd', models.IntegerField(verbose_name='Cantidad de Productos')),
                ('subTotalDet', models.IntegerField(verbose_name='Subtotal del Detalle')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AmonStore.producto')),
                ('venta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AmonStore.venta')),
            ],
        ),
        migrations.AddField(
            model_name='comuna',
            name='region',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AmonStore.region'),
        ),
    ]
