# Generated by Django 3.2.3 on 2021-06-16 00:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('AmonStore', '0003_alter_producto_fotoprod'),
    ]

    operations = [
        migrations.CreateModel(
            name='Carrito',
            fields=[
                ('idCarrito', models.AutoField(primary_key=True, serialize=False, verbose_name='Id del Carrito')),
                ('cantidadProd', models.IntegerField(verbose_name='Cantidad de Producto')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AmonStore.producto')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AmonStore.usuario')),
            ],
        ),
    ]
