# Generated by Django 3.2.3 on 2021-06-16 02:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AmonStore', '0004_carrito'),
    ]

    operations = [
        migrations.AddField(
            model_name='carrito',
            name='totalProd',
            field=models.IntegerField(default=1, verbose_name='Total a Pagar'),
            preserve_default=False,
        ),
    ]
